login:
    pattern: /login
    defaults: { _controller: CleverFormAuthenticateBundle:Security:login }

login_check:
    pattern:   /login_check
logout:
    pattern: /logout
    
send_password:
    pattern: /envoi-mot-de-passe
    defaults: { _controller: CleverFormAuthenticateBundle:Security:sendPassword}

